### ISSUE TITLE
the system keeps on speaking.

### ISSUE THREAD

**Issue by bhatritesh** [RapidWareTech/pyttsx#43]
I am new to python. Your solution almost fixed my problem. But there is another issue. After i applied your fix my system continuously goes on speaking in different manner; like french, german etc.! I have no idea why. It sounds strange but i want it to speak english only. 
I am running a virtual machine of Fedora 20 python 2.7. Please help.

**Comment by korymath** [comment]
This is happening to me as well.

**Comment by bhatritesh** [comment]
how to fix it? someone please help!

**Comment by G07cha** [comment]
@bhatritesh, could you provide code that produces problem that you described?
