### ISSUE TITLE
Speech stops halfway while speaking

### ISSUE THREAD

**Issue by manishsharma1992** [RapidWareTech/pyttsx#47]
Hi @parente,

I am using Ubuntu 16.01 LTS, I am facing problem with the speech, here is my sample code

```
import pyttsx

engine = pyttsx.init('espeak')
engine.say('Hello, I am C 4 3 2 1, What can I do for you ?')
engine.say('A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z')
engine.runAndWait()
```

When I try to execute the above code, it speaks first line clearly but it fails to speak second line. In some scenarios it doesn't speak even first line clearly.

Can you please advise, thanks in advance.

**Comment by nickgermaine** [comment]
Hey there, I recently acquired this project, so I just wanted you to know this project will be seeing activity here quite soon, and I'll have a look at all issues and attempt to resolve as many as I reasonably can.  

Thanks for logging this issue.

Cheers

**Comment by nickgermaine** [comment]
I believe you need to add engine.runAndWait() after each .say call.
